version: '2.2'
services:
  rctf:
    build: .
    restart: always
    ports:
      - '127.0.0.1:8080:80'
    networks:
      - rctf
    env_file:
      - .env
    environment:
      - PORT=80
    volumes:
      - ./conf.d:/app/conf.d
      - ./data/uploads:/app/uploads
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:6.0.6
    restart: always
    command:
      [
        "redis-server",
        "--requirepass",
        "${RCTF_REDIS_PASSWORD}"
      ]
    networks:
      - rctf
    volumes:
      - ./data/redis:/data
  postgres:
    image: postgres:12.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=${RCTF_DATABASE_PASSWORD}
      - POSTGRES_USER=rctf
      - POSTGRES_DB=rctf
    networks:
      - rctf
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  rctf: {}
