version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: weekly
    version_requirement_updates: increase_versions
  - package_manager: python
    directory: /docs
    update_schedule: weekly
    commit_message:
      prefix: build(deps-doc)
      include_scope: false
