site_name: rCTF
site_description: rCTF Documentation
site_author: redpwn
site_url: https://rctf.redpwn.net

repo_name: GitHub
repo_url: https://github.com/redpwn/rctf
edit_uri: blob/master/docs/content/

docs_dir: content

theme:
  name: material
  language: en
  features:
    - instant
  palette:
    scheme: slate
    primary: blue
    accent: blue

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: '#'
